manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/caksoylar
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: caksoylar/zen-v1+v2+mouse
      import: app/west.yml
  self:
    path: config