manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/tsangk/
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: Add-new-board-Corne-ish-Zen
      import: app/west.yml
  self:
    path: config